/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from "./core/ApiError";
export { CancelablePromise, CancelError } from "./core/CancelablePromise";
export { OpenAPI } from "./core/OpenAPI";
export type { OpenAPIConfig } from "./core/OpenAPI";

export type { AppointmentDiagnosticsDto } from "./models/AppointmentDiagnosticsDto";
export type { AppointmentDiagnosticsDtoResponseDto } from "./models/AppointmentDiagnosticsDtoResponseDto";
export type { AppointmentDiagnosticTestResultDto } from "./models/AppointmentDiagnosticTestResultDto";
export type { AppointmentDiagnosticTestsDto } from "./models/AppointmentDiagnosticTestsDto";
export type { AppointmentDto } from "./models/AppointmentDto";
export type { AppointmentDtoCollectionDto } from "./models/AppointmentDtoCollectionDto";
export type { AppointmentDtoListResponseDto } from "./models/AppointmentDtoListResponseDto";
export type { AppointmentDtoResponseDto } from "./models/AppointmentDtoResponseDto";
export type { AppointmentMedicationDrugsDto } from "./models/AppointmentMedicationDrugsDto";
export type { AppointmentMedicationsDto } from "./models/AppointmentMedicationsDto";
export type { AppointmentMedicationsDtoResponseDto } from "./models/AppointmentMedicationsDtoResponseDto";
export { AppointmentStatus } from "./models/AppointmentStatus";
export type { AssetDto } from "./models/AssetDto";
export type { AssignedPermissionsDto } from "./models/AssignedPermissionsDto";
export type { AssignedPermissionsDtoListResponseDto } from "./models/AssignedPermissionsDtoListResponseDto";
export type { AuditLogDto } from "./models/AuditLogDto";
export type { AuditLogDtoListResponseDto } from "./models/AuditLogDtoListResponseDto";
export type { AuditLogHistoryDto } from "./models/AuditLogHistoryDto";
export type { AuthenticationDto } from "./models/AuthenticationDto";
export type { AuthenticationDtoResponseDto } from "./models/AuthenticationDtoResponseDto";
export type { AuthenticationViaSpaDto } from "./models/AuthenticationViaSpaDto";
export type { AuthenticationViaSpaDtoResponseDto } from "./models/AuthenticationViaSpaDtoResponseDto";
export type { BooleanResponseDto } from "./models/BooleanResponseDto";
export type { CancelAppointmentDto } from "./models/CancelAppointmentDto";
export type { ChangePasswordDto } from "./models/ChangePasswordDto";
export { ChangeType } from "./models/ChangeType";
export type { ConsultAppointmentDto } from "./models/ConsultAppointmentDto";
export type { CreateAppointmentDiagnosticsDto } from "./models/CreateAppointmentDiagnosticsDto";
export type { CreateAppointmentDiagnosticTestsDto } from "./models/CreateAppointmentDiagnosticTestsDto";
export type { CreateAppointmentDto } from "./models/CreateAppointmentDto";
export type { CreateAppointmentMedicationDrugsDto } from "./models/CreateAppointmentMedicationDrugsDto";
export type { CreateAppointmentMedicationsDto } from "./models/CreateAppointmentMedicationsDto";
export type { CreateDiagnosticTestDto } from "./models/CreateDiagnosticTestDto";
export type { CreateDiagnosticTypeDto } from "./models/CreateDiagnosticTypeDto";
export type { CreateMedicationTypeDto } from "./models/CreateMedicationTypeDto";
export type { CreateMedicineDto } from "./models/CreateMedicineDto";
export type { CreateRoleDto } from "./models/CreateRoleDto";
export type { CreateScheduleDto } from "./models/CreateScheduleDto";
export type { CreateSpecializationDto } from "./models/CreateSpecializationDto";
export { DayOfWeek } from "./models/DayOfWeek";
export { DiagnosticStatus } from "./models/DiagnosticStatus";
export type { DiagnosticTestDto } from "./models/DiagnosticTestDto";
export type { DiagnosticTestDtoCollectionDto } from "./models/DiagnosticTestDtoCollectionDto";
export type { DiagnosticTestDtoListResponseDto } from "./models/DiagnosticTestDtoListResponseDto";
export type { DiagnosticTestDtoResponseDto } from "./models/DiagnosticTestDtoResponseDto";
export type { DiagnosticTypeDto } from "./models/DiagnosticTypeDto";
export type { DiagnosticTypeDtoCollectionDto } from "./models/DiagnosticTypeDtoCollectionDto";
export type { DiagnosticTypeDtoListResponseDto } from "./models/DiagnosticTypeDtoListResponseDto";
export type { DiagnosticTypeDtoResponseDto } from "./models/DiagnosticTypeDtoResponseDto";
export type { DoctorDirectoryDto } from "./models/DoctorDirectoryDto";
export type { DoctorProfileDto } from "./models/DoctorProfileDto";
export type { DoctorProfileDtoCollectionDto } from "./models/DoctorProfileDtoCollectionDto";
export type { DoctorProfileDtoListResponseDto } from "./models/DoctorProfileDtoListResponseDto";
export type { DoctorProfileDtoResponseDto } from "./models/DoctorProfileDtoResponseDto";
export type { DoctorRecommendationResultDto } from "./models/DoctorRecommendationResultDto";
export type { DoctorRecommendationResultDtoResponseDto } from "./models/DoctorRecommendationResultDtoResponseDto";
export type { EmailOutboxDto } from "./models/EmailOutboxDto";
export type { EmailOutboxDtoCollectionDto } from "./models/EmailOutboxDtoCollectionDto";
export type { EmailOutboxDtoListResponseDto } from "./models/EmailOutboxDtoListResponseDto";
export type { EmailOutboxDtoResponseDto } from "./models/EmailOutboxDtoResponseDto";
export { EmailProcess } from "./models/EmailProcess";
export { FieldDataType } from "./models/FieldDataType";
export type { ForgotPasswordConfirmationDto } from "./models/ForgotPasswordConfirmationDto";
export type { ForgotPasswordResetDto } from "./models/ForgotPasswordResetDto";
export { Gender } from "./models/Gender";
export type { GrantPermissionsDto } from "./models/GrantPermissionsDto";
export type { GrantResourcePermissionDto } from "./models/GrantResourcePermissionDto";
export type { Login2FactorAuthenticationDto } from "./models/Login2FactorAuthenticationDto";
export type { LoginDto } from "./models/LoginDto";
export { LoginEventType } from "./models/LoginEventType";
export type { LoginSpaDto } from "./models/LoginSpaDto";
export type { LoginSpaDtoResponseDto } from "./models/LoginSpaDtoResponseDto";
export { LoginStatus } from "./models/LoginStatus";
export type { MedicalRecordDto } from "./models/MedicalRecordDto";
export type { MedicationTypeDto } from "./models/MedicationTypeDto";
export type { MedicationTypeDtoCollectionDto } from "./models/MedicationTypeDtoCollectionDto";
export type { MedicationTypeDtoListResponseDto } from "./models/MedicationTypeDtoListResponseDto";
export type { MedicationTypeDtoResponseDto } from "./models/MedicationTypeDtoResponseDto";
export type { MedicineDto } from "./models/MedicineDto";
export type { MedicineDtoCollectionDto } from "./models/MedicineDtoCollectionDto";
export type { MedicineDtoListResponseDto } from "./models/MedicineDtoListResponseDto";
export type { MedicineDtoResponseDto } from "./models/MedicineDtoResponseDto";
export { Orientation } from "./models/Orientation";
export { OutboxStatus } from "./models/OutboxStatus";
export type { PatientProfileDto } from "./models/PatientProfileDto";
export type { PatientProfileDtoResponseDto } from "./models/PatientProfileDtoResponseDto";
export type { PermissionDto } from "./models/PermissionDto";
export type { ProfileDto } from "./models/ProfileDto";
export type { ProfileDtoResponseDto } from "./models/ProfileDtoResponseDto";
export type { RoleDto } from "./models/RoleDto";
export type { RoleDtoCollectionDto } from "./models/RoleDtoCollectionDto";
export type { RoleDtoListResponseDto } from "./models/RoleDtoListResponseDto";
export type { RoleDtoResponseDto } from "./models/RoleDtoResponseDto";
export type { ScheduleDto } from "./models/ScheduleDto";
export type { SpecializationDto } from "./models/SpecializationDto";
export type { SpecializationDtoCollectionDto } from "./models/SpecializationDtoCollectionDto";
export type { SpecializationDtoListResponseDto } from "./models/SpecializationDtoListResponseDto";
export type { SpecializationDtoResponseDto } from "./models/SpecializationDtoResponseDto";
export type { TimeslotDto } from "./models/TimeslotDto";
export type { TimeslotDtoListResponseDto } from "./models/TimeslotDtoListResponseDto";
export type { TokenDto } from "./models/TokenDto";
export type { TokenDtoResponseDto } from "./models/TokenDtoResponseDto";
export type { TwoFactorSetupDto } from "./models/TwoFactorSetupDto";
export type { TwoFactorSetupDtoResponseDto } from "./models/TwoFactorSetupDtoResponseDto";
export type { TwoFactorStatusDto } from "./models/TwoFactorStatusDto";
export type { TwoFactorStatusDtoResponseDto } from "./models/TwoFactorStatusDtoResponseDto";
export type { TwoFactorVerificationDto } from "./models/TwoFactorVerificationDto";
export type { UpdateAppointmentDiagnosticTestResultDto } from "./models/UpdateAppointmentDiagnosticTestResultDto";
export type { UpdateAppointmentDto } from "./models/UpdateAppointmentDto";
export type { UpdateDiagnosticTestDto } from "./models/UpdateDiagnosticTestDto";
export type { UpdateDiagnosticTypeDto } from "./models/UpdateDiagnosticTypeDto";
export type { UpdateDoctorProfileDto } from "./models/UpdateDoctorProfileDto";
export type { UpdateMedicationTypeDto } from "./models/UpdateMedicationTypeDto";
export type { UpdateMedicineDto } from "./models/UpdateMedicineDto";
export type { UpdateProfileDto } from "./models/UpdateProfileDto";
export type { UpdateRoleDto } from "./models/UpdateRoleDto";
export type { UpdateScheduleDto } from "./models/UpdateScheduleDto";
export type { UpdateSpecializationDto } from "./models/UpdateSpecializationDto";
export type { UserDto } from "./models/UserDto";
export type { UserDtoCollectionDto } from "./models/UserDtoCollectionDto";
export type { UserDtoListResponseDto } from "./models/UserDtoListResponseDto";
export type { UserDtoResponseDto } from "./models/UserDtoResponseDto";
export type { UserLoginLogDto } from "./models/UserLoginLogDto";
export type { UserLoginLogDtoCollectionDto } from "./models/UserLoginLogDtoCollectionDto";
export type { UserLoginLogDtoListResponseDto } from "./models/UserLoginLogDtoListResponseDto";
export type { UserLoginLogDtoResponseDto } from "./models/UserLoginLogDtoResponseDto";

export { AppointmentService } from "./services/AppointmentService";
export { AppointmentDiagnosticsService } from "./services/AppointmentDiagnosticsService";
export { AppointmentMedicationsService } from "./services/AppointmentMedicationsService";
export { AuditLogService } from "./services/AuditLogService";
export { AuthenticationService } from "./services/AuthenticationService";
export { DiagnosticTestService } from "./services/DiagnosticTestService";
export { DiagnosticTypeService } from "./services/DiagnosticTypeService";
export { DoctorService } from "./services/DoctorService";
export { DoctorRecommendationService } from "./services/DoctorRecommendationService";
export { EmailOutboxService } from "./services/EmailOutboxService";
export { MedicationTypeService } from "./services/MedicationTypeService";
export { MedicineService } from "./services/MedicineService";
export { PatientService } from "./services/PatientService";
export { PermissionService } from "./services/PermissionService";
export { ProfileService } from "./services/ProfileService";
export { RoleService } from "./services/RoleService";
export { SpecializationService } from "./services/SpecializationService";
export { UserService } from "./services/UserService";
export { UserLoginLogService } from "./services/UserLoginLogService";
